---
- name: set up webserver
  hosts: all
  become: true
  tasks:
    - name: Install the NGINX application on localhost
      apt:
        name: nginx
        state: present
    - name: start nginx
      service:
        name: nginx
        state: started
        enabled: yes  # if you want to also enable nginx
